plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android") version "2.4.20"
}

group = "com.example.signalr_chat_plugin"
version = "1.0"

android {
    namespace = "com.example.signalr_chat_plugin"
    compileSdk = 36

    sourceSets {
        getByName("main").kotlin.srcDirs("src/main/kotlin")
    }

    defaultConfig {
        minSdk = 16
        targetSdk = 36
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    lint {
        disable += "InvalidPackage"
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_1_8
    }
}

dependencies {
    implementation("com.microsoft.signalr:signalr:5.0.0")
    implementation("com.squareup.okhttp3:okhttp:4.9.1")
}